// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVtwQnwjw1hop4edMie9eY_ILvG_fuXEI',
    appId: '1:685282199422:web:dbf07271045a38365cd52f',
    messagingSenderId: '685282199422',
    projectId: 'bytebox-96b6a',
    authDomain: 'bytebox-96b6a.firebaseapp.com',
    storageBucket: 'bytebox-96b6a.firebasestorage.app',
    measurementId: 'G-960BDMRBJZ',
    databaseURL: "https://deepa-skitchenadmin-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhd7mLY58F78UQmObL_G2zpbLNPiPXDCA',
    appId: '1:685282199422:android:7c98b792c1948b2b5cd52f',
    messagingSenderId: '685282199422',
    projectId: 'bytebox-96b6a',
    storageBucket: 'bytebox-96b6a.firebasestorage.app',
    databaseURL: "https://deepa-skitchenadmin-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYS0i2NaYtWXFjD5IohVHoREygxIMU8NU',
    appId: '1:685282199422:ios:a95ad3f60314f2be5cd52f',
    messagingSenderId: '685282199422',
    projectId: 'bytebox-96b6a',
    storageBucket: 'bytebox-96b6a.firebasestorage.app',
    iosBundleId: 'com.example.bytebox',
    databaseURL: "https://bytebox-96b6a-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYS0i2NaYtWXFjD5IohVHoREygxIMU8NU',
    appId: '1:685282199422:ios:a95ad3f60314f2be5cd52f',
    messagingSenderId: '685282199422',
    projectId: 'bytebox-96b6a',
    storageBucket: 'bytebox-96b6a.firebasestorage.app',
    iosBundleId: 'com.example.bytebox',
    databaseURL: "https://bytebox-96b6a-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVtwQnwjw1hop4edMie9eY_ILvG_fuXEI',
    appId: '1:685282199422:web:fee48cdbe6c46ae75cd52f',
    messagingSenderId: '685282199422',
    projectId: 'bytebox-96b6a',
    authDomain: 'bytebox-96b6a.firebaseapp.com',
    storageBucket: 'bytebox-96b6a.firebasestorage.app',
    measurementId: 'G-TXBHW4LZ27',
    databaseURL: "https://bytebox-96b6a-default-rtdb.firebaseio.com/",
  );

}